### ISSUE TITLE
Breast bones not deforming

### ISSUE THREAD

**Issue by catprisbrey** [catprisbrey/Rigodotify#1]
There is an issue present, the generated Godot Metarig is good, and the initial Rigify Rig it generates works properly to deform the breast bone vertices, but once Godotified using the plugin button, the breast bones no longer deform the mesh. 

Needs investigation and a fix.

**Comment by catprisbrey** [comment]
Spent some time exploring the issue, found that former contraints were lost. i've re-added them in code and hopefully these new settings will solve the issues for breast, jaw, and eye deformations. Fixed in the maintenance release Rigodotify v1.0.4.

**Comment by jogly** [comment]
There seems to be a similar issue with the shoulders not deforming, I notice that `DEF-shoulder.L` and `R` do not have the copy transforms constraint.

**Comment by catprisbrey** [comment]
I'll run a few test to confirm and should have a fix soon..if its anything like the breast bones, it won't be hard to punch a fix into the code.

This late on a Friday though I may have to wait until tomorrow or Sunday to take a look.

**Comment by jogly** [comment]
> I'll run a few test to confirm and should have a fix soon..if its anything like the breast bones, it won't be hard to punch a fix into the code.
> 
> This late on a Friday though I may have to wait until tomorrow or Sunday to take a look.

<3 I didn't expect a response until next week so you're already exceeding expectations!

**Comment by jogly** [comment]
> I did some rigs today with it and found the shoulders were all moving and deforming fine. Though I haven't double checked specifically the constraints on the bones, I was just doing some animating and was moving shoulders around and not digging too deep.
> 
> Were your shoulders not moving at all? Or just missing some specific constraints?

Interesting! The specific issue I'm having is the shoulder deforming bones are not constrained to the rig's shoulder control bones, the ones under `MCH-torso.parent`.

<img width="304" alt="image" src="https://github.com/catprisbrey/Rigodotify/assets/1476969/21de13b8-0fe1-4328-95b2-2f73103f04f8">

Notice in that image there are no constraints on the shoulders, like there are in the breast bones after your previous patch. I can also confirm that the `DEF-shoulder.L` bone is weight painted. 

https://github.com/catprisbrey/Rigodotify/assets/1476969/c094cd7c-618b-4b0a-bbc3-a16821338841

**Comment by catprisbrey** [comment]
Great recon work, great screenshots/gifs. This made itt MUCH easier to see exactly what you mean. The recent commit Should take care of it this. I'll bundle up and upload a new zip of the newest version too. Thanks for your assistance with this @jogly !
