### ISSUE TITLE
Wrong deform bone lenght in right leg

### ISSUE THREAD

**Issue by BasilYes** [catprisbrey/Rigodotify#2]
I'm using last (1.0.6) version
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/4872fd37-a26f-4c8e-82b0-382f376a1875)

**Comment by catprisbrey** [comment]
So sorry i didn't see this issue come in. I've been overhauling a ton of the scripts the past week. In my attempt to recreate the issue in the latest build ( v1.1.0)  it looks good now. Could you try it in the new latest and let me know? Sorry!

**Comment by BasilYes** [comment]
Thanks for your addon, don't be sorry. Issues is part of any work. Now all works perfect for all variations 
![image](https://github.com/catprisbrey/Rigodotify/assets/36816595/b13856c2-ac3c-4da4-9dcd-05d864008863)

**Comment by BasilYes** [comment]
Oh. and I'm want to share with you some similar addons. May be you can be inspired by some of them. [One close to yours. addon](https://github.com/SAM-tak/BlenderGameRig) [Other just bunch of riggify rigs.](https://github.com/Arminando/GameRig)

**Comment by catprisbrey** [comment]
I'm familiar with these ones for sure. I used them off and on for a while but then i just wanted something very specific, and figured I'd rather make it myself. I'd always wanted to learn it better to understand it from the inside, and not just use a tool that i couldn't fix if something went wrong.

**Comment by BasilYes** [comment]
Your addon the best out there, cause I can create custom rigify rig and cleanup it's with your addon.
